### ISSUE TITLE
Feature suggestion: Kill existing process if running when F5 is pressed

### ISSUE THREAD

**Issue by sayaka-sh** [discretegames/f5anything#1]
Currently, pressing F5 with this extension while a process is already running in the terminal will just send the text to it on top of the current process, so the user is required to manually halt the process themselves.
It would be really convenient to be able to just press F5 once and have the previous process be stopped automatically by the extension. Other run types (like Python) already have the option to do this.

**Comment by discretegames** [comment]
This is a good idea, I may get around to implementing it. Probably in the form of a `"toggle"` boolean launch configuration property that defaults to false, but when true will enable this behavior.

**Comment by discretegames** [comment]
Sorry, I'm closing this as infeasible - at least not in the way desired. As far as I could tell there's no simple way to see if a process is running in a VSCode integrated terminal.

A better way might be to have an option for a shortcut key like Shift+F5 to send Ctrl+C to the terminal. but it looks like there are already extensions out there that can do this better than I'd be able to: https://stackoverflow.com/a/52735332
