### ISSUE TITLE
Add ability to disable switching to the Debug pane on F5

### ISSUE THREAD

**Issue by fatcerberus** [discretegames/f5anything#3]
Pressing F5 automatically switches to the Debug pane, which isn't useful when using F5Anything, and having to switch back to the Files pane every time gets annoying fast.  Would be great to be able to disable this behavior, if possible.

**Comment by sayaka-sh** [comment]
This doesn't happen for me, pressing F5 doesn't switch the pane at all, both with this extension and another launch type I tried. This may be a bug, or something VSCode itself allows changing (although I couldn't find anything).

**Comment by discretegames** [comment]
It switches for me too and I agree it's an annoyance. It [looks like there's a VSCode setting for this](https://stackoverflow.com/a/53094822) you can put in your project's settings.json:

```json
{
    "debug.openDebug": "neverOpen",
}
```

That stops the auto switching for me. Hopefully works for you too @fatcerberus  (maybe @spectreseven1138 already has that set).

Though I realize having this builtin and specific to F5Anything would be more ideal. If there's a desire for that feel free to comment/open another issue and I may be able to look into it.

(Curiously `"debug.openDebug": "openOnDebugBreak"` is also an option but it does still switch, even though F5Anything doesn't use breakpoints, so I'm not sure what's going on there.)

**Comment by discretegames** [comment]
A VSCode setting can fix this behavior.

**Comment by fatcerberus** [comment]
Yeah, I did end up finding that setting after I posted the issue.  The default is `openOnDebugBreak` so I was very confused why it was still switching.  If F5Anything could do something to prevent that, that’d be great, but if not I can deal with the settings.json fix for now.
