### ISSUE TITLE
Is there a way to F5 an extension command? 

### ISSUE THREAD

**Issue by crabdancing** [discretegames/f5anything#4]
I am trying to build a general-purpose work environment where I can pick a single 'run the thing' key for every application (which, in my case, includes a wide variety of tooling).

Rather than an external shell command, my use case would be best fit by calling an internal 'feature contribution' command (in this case, `picowgo.upload`).

Is there a convenient way that this extension can accommodate that use case that I'm missing? And if not, would you consider adding it? :)

**Comment by discretegames** [comment]
This was a good idea and [easy](https://code.visualstudio.com/api/extension-guides/command#programmatically-executing-a-command) so I implemented it for version 1.2.0!

You  can now add a `"vscCommand"` to the launch configuration in place of (or in addition to) the normal `"command"` to specify the ID of a VSCode command to run.

So in your case the launch configuration might look like:
```json
{
    "name": "F5 Anything: Pico-Go Upload",
    "type": "f5anything",
    "request": "launch",
    "vscCommand": "picogo.upload",
}
```

It's all explained in the readme/marketplace page: <https://marketplace.visualstudio.com/items?itemName=discretegames.f5anything>

Please tell me if you run into any issues with it 👍
Closing this issue as completed.
